const API=(window.NM_CONFIG?.API_BASE_URL||"").replace(/\/$/,"");
let token=localStorage.getItem("nm_token")||null; let currentView="overview"; let customers=[]; let payments=[]; let devices=[]; let enrollments=[]; let activity=[]; let stats={};
const $=id=>document.getElementById(id), esc=v=>String(v??"").replace(/[&<>\"]/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[s]));
const money=v=>`Rs. ${Number(v||0).toLocaleString("en-PK",{maximumFractionDigits:2})}`;
const date=v=>v?new Date(String(v).replace(" ","T")+(!String(v).endsWith("Z")?"Z":"")).toLocaleString():"—";
function toast(msg,type=""){const el=document.createElement("div");el.className=`toast ${type}`;el.textContent=msg;$("toastHost").appendChild(el);setTimeout(()=>el.remove(),3200)}
async function api(path,opts={}){const res=await fetch(API+path,{...opts,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{}) ,...(opts.headers||{})}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`Request failed (${res.status})`);return data}
function statusBadge(status){const map={pending:["pending","Pending"],unlocked:["enrolled","Enrolled"],locked:["locked","Locked"],release_pending:["releasing","Releasing"],released:["released","Released"]};const m=map[status]||["","Unknown"];return `<span class="status ${m[0]}">${m[1]}</span>`}
function render(){
  const titles={overview:"Overview",customers:"Customers",payments:"Payments",devices:"Devices",enrollments:"Enrollments",activity:"Activity",settings:"Settings"};
  $("pageTitle").textContent=titles[currentView]; $("pageEyebrow").textContent=window.NM_SHOP_NAME||"Nadeem Mobiles";
  document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===currentView));
  const views={overview:renderOverview,customers:renderCustomers,payments:renderPayments,devices:renderDevices,enrollments:renderEnrollments,activity:renderActivity,settings:renderSettings};
  $("content").innerHTML=views[currentView](); bindViewActions();
}
function renderOverview(){const paid=Number(stats.paid_amount||0), total=Number(stats.total_amount||0), outstanding=Number(stats.outstanding||0), pct=total?Math.min(100,Math.round(paid/total*100)):0;const recent=activity.slice(0,7);return `<div class="page-grid metrics"><div class="metric"><div class="label">Customers</div><div class="value">${stats.total||0}</div><div class="sub">All customer records</div></div><div class="metric good"><div class="label">Enrolled devices</div><div class="value">${Number(stats.active||0)+Number(stats.locked||0)}</div><div class="sub">${stats.active||0} unlocked · ${stats.locked||0} locked</div></div><div class="metric warn"><div class="label">Outstanding</div><div class="value">${money(outstanding)}</div><div class="sub">${stats.overdue||0} overdue · ${stats.dueSoon||0} due in 7 days</div></div><div class="metric"><div class="label">Collected</div><div class="value">${money(paid)}</div><div class="sub">${pct}% of recorded total</div></div></div><div class="page-grid two-col" style="margin-top:16px"><section class="card"><div class="card-head"><h3>Payment progress</h3><span class="muted">${pct}% collected</span></div><div class="card-body"><div class="progress-row"><span>Total</span><strong>${money(total)}</strong></div><div class="bar"><div style="width:${pct}%"></div></div><div class="progress-row" style="margin-top:12px"><span>Paid</span><strong>${money(paid)}</strong></div><div class="progress-row"><span>Outstanding</span><strong>${money(outstanding)}</strong></div></div></section><section class="card"><div class="card-head"><h3>Quick actions</h3></div><div class="card-body"><div class="quick-grid"><button class="quick" data-open="customer"><strong>+ New customer</strong><span>Generate a 6-digit pairing code</span></button><button class="quick" data-view="payments"><strong>Record payment</strong><span>Update customer balance</span></button><button class="quick" data-view="devices"><strong>Manage devices</strong><span>Lock, unlock or release</span></button><button class="quick" data-view="enrollments"><strong>View enrollments</strong><span>Track pairing status</span></button></div></div></section></div><section class="card" style="margin-top:16px"><div class="card-head"><h3>Recent activity</h3><button class="mini" data-view="activity">View all</button></div><div class="activity-list">${recent.length?recent.map(renderActivityRow).join(""):`<div class="empty">No activity yet.</div>`}</div></section>`}
function renderCustomers(){return `<div class="toolbar"><input class="search" id="customerSearch" placeholder="Search name or phone…"><button class="primary" data-open="customer">+ New customer</button></div><section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Customer</th><th>Device</th><th>Balance</th><th>Due</th><th>Status</th><th>Actions</th></tr></thead><tbody>${customers.length?customers.map(c=>`<tr><td><div class="customer-name">${esc(c.name)}</div><div class="customer-meta">${esc(c.phone_number)}</div></td><td>${esc(c.device_model||"Not paired")}</td><td><div class="money">${money(c.outstanding)}</div><div class="customer-meta">${money(c.paid_amount)} paid</div></td><td>${c.next_due_date?esc(c.next_due_date):"—"}${Number(c.overdue)?`<div class="customer-meta" style="color:var(--bad)">Overdue</div>`:""}</td><td>${statusBadge(c.status)}</td><td><div class="actions"><button class="mini" data-edit="${c.id}">Details</button><button class="mini" data-pay="${c.id}">Payment</button>${c.status==="unlocked"?`<button class="mini lock" data-lock="${c.id}">Lock</button>`:""}${c.status==="locked"?`<button class="mini unlock" data-unlock="${c.id}">Unlock</button>`:""}${["unlocked","locked"].includes(c.status)?`<button class="mini release" data-release="${c.id}">Release</button>`:""}</div></td></tr>`).join(""):`<tr><td colspan="6" class="empty">No customers yet.</td></tr>`}</tbody></table></div></section>`}
function renderPayments(){return `<div class="toolbar"><div><strong>${payments.length}</strong> payments recorded</div><select id="paymentFilter"><option value="all">All payments</option></select></div><section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Customer</th><th>Amount</th><th>Paid at</th><th>Reference</th><th>Note</th><th>Action</th></tr></thead><tbody>${payments.length?payments.map(p=>`<tr><td><div class="customer-name">${esc(p.customer_name)}</div><div class="customer-meta">${esc(p.phone_number)}</div></td><td class="money">${money(p.amount)}</td><td>${esc(date(p.paid_at))}</td><td>${esc(p.reference||"—")}</td><td>${esc(p.note||"—")}</td><td><button class="mini danger" data-delpay="${p.id}">Delete</button></td></tr>`).join(""):`<tr><td colspan="6" class="empty">No payments recorded.</td></tr>`}</tbody></table></div></section>`}
function renderDevices(){const list=devices.filter(d=>d.status!=="released");return `<div class="toolbar"><div><strong>${list.length}</strong> managed devices</div><button class="mini" data-view="enrollments">Open enrollment queue</button></div><section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Device</th><th>Customer</th><th>Status</th><th>Last seen</th><th>Controls</th></tr></thead><tbody>${list.length?list.map(d=>`<tr><td><div class="customer-name">${esc(d.device_model||"Unknown device")}</div><div class="customer-meta">Device ID #${d.id}</div></td><td><div class="customer-name">${esc(d.name)}</div><div class="customer-meta">${esc(d.phone_number)}</div></td><td>${statusBadge(d.status)}</td><td>${esc(date(d.last_seen))}</td><td><div class="actions">${d.status==="unlocked"?`<button class="mini lock" data-lock="${d.id}">Lock</button>`:""}${d.status==="locked"?`<button class="mini unlock" data-unlock="${d.id}">Unlock</button>`:""}${["unlocked","locked"].includes(d.status)?`<button class="mini release" data-release="${d.id}">Release</button>`:""}<button class="mini" data-edit="${d.id}">Details</button></div></td></tr>`).join(""):`<tr><td colspan="5" class="empty">No enrolled devices.</td></tr>`}</tbody></table></div></section>`}
function renderEnrollments(){return `<div class="toolbar"><div>Enrollment lifecycle</div><button class="primary" data-open="customer">+ New enrollment</button></div><section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Customer</th><th>Pairing code</th><th>Status</th><th>Device</th><th>Created</th><th>Action</th></tr></thead><tbody>${enrollments.length?enrollments.map(e=>`<tr><td><div class="customer-name">${esc(e.name)}</div><div class="customer-meta">${esc(e.phone_number)}</div></td><td><strong style="letter-spacing:3px">${e.status==='pending'?esc(e.pairing_code):'••••••'}</strong></td><td>${statusBadge(e.status)}</td><td>${esc(e.device_model||"Awaiting pairing")}</td><td>${esc(date(e.created_at))}</td><td><div class="actions">${e.status==='pending'?`<button class="mini" data-code="${e.id}">Show code</button>`:""}${['unlocked','locked'].includes(e.status)?`<button class="mini release" data-release="${e.id}">Release</button>`:""}${e.status==='released'?`<button class="mini" data-reenroll="${e.id}">Re-enroll</button><button class="mini danger" data-remove="${e.id}">Remove</button>`:""}</div></td></tr>`).join(""):`<tr><td colspan="6" class="empty">No enrollments found.</td></tr>`}</tbody></table></div></section>`}
function renderActivity(){return `<section class="card"><div class="card-head"><h3>Event history</h3><span class="muted">Latest 150 events</span></div><div class="activity-list">${activity.length?activity.map(renderActivityRow).join(""):`<div class="empty">No activity yet.</div>`}</div></section>`}
function renderActivityRow(a){const label=a.action.replaceAll("_"," ");return `<div class="activity"><div class="activity-dot"></div><div><strong>${esc(a.customer_name||"System")} — ${esc(label)}</strong><div class="detail">${esc(a.detail||"")}</div></div><time>${esc(date(a.at))}</time></div>`}
function renderSettings(){const origin=location.origin;return `<div class="page-grid two-col"><section class="card"><div class="card-head"><h3>Shop settings</h3></div><div class="card-body settings-list"><div class="setting"><div><strong>Shop name</strong><span>Displayed in the app and dashboard</span></div><strong>Nadeem Mobiles</strong></div><div class="setting"><div><strong>Dashboard URL</strong><span>Current page origin</span></div><strong>${esc(origin)}</strong></div><div class="setting"><div><strong>Backend URL</strong><span>Configured in dashboard/config.js</span></div><strong>${esc(API||"Same origin / not configured")}</strong></div></div></section><section class="card"><div class="card-head"><h3>Release policy</h3></div><div class="card-body"><div class="notice">Enrolled phones keep Factory Reset blocked and Uninstall blocked until the shop sends Release. Remove is disabled while a device is still enrolled.</div><div class="notice" style="margin-top:10px">Release is acknowledged by the phone before the backend marks the enrollment as Released.</div></div></section></div>`}
function modal(title,body){return `<div class="modal-backdrop" data-close-modal><div class="modal" role="dialog" aria-modal="true"><div class="modal-head"><h3>${title}</h3><button class="ghost" data-close-modal>Close</button></div><div class="modal-body">${body}</div></div></div>`}
function openModal(html){$("modalHost").innerHTML=html}
function closeModal(){$("modalHost").innerHTML=""}
function customerForm(){return modal("New customer & enrollment",`<form id="customerForm" class="form-grid"><label>Customer name<input id="fName" required></label><label>Phone number<input id="fPhone" placeholder="03XX-XXXXXXX" required></label><label>Total sale amount<input id="fTotal" type="number" min="0" step="0.01" placeholder="0"></label><label>Installment amount<input id="fInstallment" type="number" min="0" step="0.01" placeholder="0"></label><label>Next due date<input id="fDue" type="date"></label><label>Notes<input id="fNotes" placeholder="Optional notes"></label><div class="span2 notice">After creation, the dashboard generates a one-time 6-digit pairing code. The customer app only asks for that code.</div><div class="span2 modal-actions"><button type="button" class="ghost" data-close-modal>Cancel</button><button class="primary" type="submit">Create & show code</button></div></form>`)}
function codeModal(c){return modal("Pairing code",`<div class="notice">Give this code to the customer. It is entered only in the Nadeem Mobiles app. No server address is entered on the phone.</div><div class="code-box"><div class="code">${esc(c.pairingCode)}</div><div class="muted" style="margin-top:6px">${esc(c.name)}</div></div><div class="modal-actions"><button class="primary" data-close-modal>Done</button></div>`)}
function paymentModal(c){return modal(`Record payment — ${esc(c.name)}`,`<form id="paymentForm" class="form-grid" data-customer-id="${c.id}"><label>Amount<input id="pAmount" type="number" min="0.01" step="0.01" required></label><label>Reference<input id="pRef" placeholder="Receipt / transaction #"></label><label class="span2">Note<input id="pNote" placeholder="Optional"></label><div class="span2 notice">Current outstanding: <strong>${money(c.outstanding)}</strong></div><div class="span2 modal-actions"><button type="button" class="ghost" data-close-modal>Cancel</button><button class="primary" type="submit">Save payment</button></div></form>`)}
async function showCustomer(id){const c=customers.find(x=>Number(x.id)===Number(id));if(!c)return;openModal(modal(`Customer details — ${esc(c.name)}`,`<div class="detail-grid"><div class="detail-tile"><span>Phone</span><strong>${esc(c.phone_number)}</strong></div><div class="detail-tile"><span>Status</span><strong>${statusBadge(c.status)}</strong></div><div class="detail-tile"><span>Device</span><strong>${esc(c.device_model||"Not paired")}</strong></div><div class="detail-tile"><span>Total</span><strong>${money(c.total_amount)}</strong></div><div class="detail-tile"><span>Paid</span><strong>${money(c.paid_amount)}</strong></div><div class="detail-tile"><span>Outstanding</span><strong>${money(c.outstanding)}</strong></div></div><div style="margin-top:14px" class="notice">Next due: <strong>${esc(c.next_due_date||"Not set")}</strong><br>Last seen: <strong>${esc(date(c.last_seen))}</strong></div><div style="margin-top:14px" class="note-box">${esc(c.notes||"No notes")}</div><div class="modal-actions"><button class="ghost" data-close-modal>Close</button>${c.status==='unlocked'?`<button class="mini lock" data-lock="${c.id}">Lock</button>`:""}${c.status==='locked'?`<button class="mini unlock" data-unlock="${c.id}">Unlock</button>`:""}${['unlocked','locked'].includes(c.status)?`<button class="mini release" data-release="${c.id}">Release</button>`:""}</div>`));}
async function loadAll(){try{[stats,customers,payments,devices,enrollments,activity]=await Promise.all([api('/api/stats'),api('/api/customers'),api('/api/payments'),api('/api/devices'),api('/api/enrollments'),api('/api/activity')]);render();$("connectionLabel").textContent="Backend connected";$("connectionLabel").previousElementSibling.classList.add("ok");}catch(e){$("connectionLabel").textContent="Backend unavailable";if(e.message.toLowerCase().includes("session"))logout();else toast(e.message,'bad')}}
function logout(){token=null;localStorage.removeItem("nm_token");$("appView").classList.add("hidden");$("loginView").classList.remove("hidden")}
function bindViewActions(){
  $("content").querySelectorAll("[data-view]").forEach(el=>el.addEventListener("click",()=>{currentView=el.dataset.view;render()}));
  $("content").querySelectorAll("[data-open='customer']").forEach(el=>el.addEventListener("click",()=>openModal(customerForm())));
  $("content").querySelectorAll("[data-close-modal]").forEach(el=>el.addEventListener("click",closeModal));
  const s=$("customerSearch");if(s)s.addEventListener("input",()=>{const q=s.value.toLowerCase();document.querySelectorAll('#content tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')});
  $("content").querySelectorAll("[data-edit]").forEach(el=>el.addEventListener("click",()=>showCustomer(el.dataset.edit)));
  $("content").querySelectorAll("[data-pay]").forEach(el=>el.addEventListener("click",()=>{const c=customers.find(x=>String(x.id)===el.dataset.pay);if(c)openModal(paymentModal(c))}));
  $("content").querySelectorAll("[data-lock]").forEach(el=>el.addEventListener("click",()=>deviceAction(el.dataset.lock,'lock')));
  $("content").querySelectorAll("[data-unlock]").forEach(el=>el.addEventListener("click",()=>deviceAction(el.dataset.unlock,'unlock')));
  $("content").querySelectorAll("[data-release]").forEach(el=>el.addEventListener("click",()=>releaseDevice(el.dataset.release)));
  $("content").querySelectorAll("[data-remove]").forEach(el=>el.addEventListener("click",()=>removeCustomer(el.dataset.remove)));
  $("content").querySelectorAll("[data-reenroll]").forEach(el=>el.addEventListener("click",()=>reEnroll(el.dataset.reenroll)));
  $("content").querySelectorAll("[data-code]").forEach(el=>el.addEventListener("click",async()=>{try{const c=customers.find(x=>String(x.id)===el.dataset.code);openModal(codeModal({name:c.name,pairingCode:c.pairing_code}))}catch(e){toast(e.message,'bad')}}));
  $("content").querySelectorAll("[data-delpay]").forEach(el=>el.addEventListener("click",()=>deletePayment(el.dataset.delpay)));
  const cf=$("customerForm");if(cf)cf.addEventListener("submit",createCustomer);const pf=$("paymentForm");if(pf)pf.addEventListener("submit",e=>submitPayment(e));
}
async function createCustomer(e){e.preventDefault();try{const d=await api('/api/customers',{method:'POST',body:JSON.stringify({name:$('fName').value.trim(),phoneNumber:$('fPhone').value.trim(),totalAmount:$('fTotal').value,installmentAmount:$('fInstallment').value,nextDueDate:$('fDue').value,notes:$('fNotes').value.trim()})});toast('Customer created','good');await loadAll();const c=customers.find(x=>Number(x.id)===Number(d.id));closeModal();if(c)openModal(codeModal({name:c.name,pairingCode:d.pairingCode}))}catch(e){toast(e.message,'bad')}}
async function submitPayment(e){e.preventDefault();try{const c=customers.find(x=>String(x.id)===e.currentTarget.dataset.customerId);if(!c)throw new Error('Customer not found.');await api(`/api/payments/customer/${c.id}`,{method:'POST',body:JSON.stringify({amount:$('pAmount').value,reference:$('pRef').value.trim(),note:$('pNote').value.trim()})});closeModal();toast('Payment saved','good');await loadAll()}catch(e){toast(e.message,'bad')}}
async function deviceAction(id,action){try{await api(`/api/customers/${id}/${action}`,{method:'POST'});toast(action==='lock'?'Lock command sent':'Unlock command sent','good');await loadAll()}catch(e){toast(e.message,'bad')}}
async function releaseDevice(id){const c=customers.find(x=>Number(x.id)===Number(id));if(!c)return;if(!confirm(`Release ${c.name}?\n\nThe phone will lose Nadeem Mobiles management. Uninstall becomes available only after the phone confirms the release.`))return;try{await api(`/api/customers/${id}/release`,{method:'POST'});toast('Release request sent. Waiting for phone acknowledgement…','good');await loadAll()}catch(e){toast(e.message,'bad')}}
async function reEnroll(id){const c=customers.find(x=>Number(x.id)===Number(id));if(!c)return;if(!confirm(`Create a fresh 6-digit pairing code for ${c.name}?`))return;try{const d=await api(`/api/customers/${id}/re-enroll`,{method:'POST'});toast('New enrollment created','good');await loadAll();const fresh=customers.find(x=>Number(x.id)===Number(id));closeModal();if(fresh)openModal(codeModal({name:fresh.name,pairingCode:d.pairingCode}))}catch(e){toast(e.message,'bad')}}
async function removeCustomer(id){const c=customers.find(x=>Number(x.id)===Number(id));if(!confirm(`Remove ${c?.name||'this customer'}? This deletes customer/payment/event data.`))return;try{await api(`/api/customers/${id}`,{method:'DELETE'});toast('Customer removed','good');await loadAll()}catch(e){toast(e.message,'bad')}}
async function deletePayment(id){if(!confirm('Delete this payment record?'))return;try{await api(`/api/payments/${id}`,{method:'DELETE'});toast('Payment deleted','good');await loadAll()}catch(e){toast(e.message,'bad')}}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginError").textContent="";try{const d=await api('/api/login',{method:'POST',body:JSON.stringify({username:$('loginUsername').value.trim(),password:$('loginPassword').value})});token=d.token;localStorage.setItem('nm_token',token);window.NM_SHOP_NAME=d.shopName;$("loginView").classList.add('hidden');$("appView").classList.remove('hidden');await loadAll()}catch(e){$("loginError").textContent=e.message}});
$("logoutBtn").addEventListener("click",logout);$("refreshBtn").addEventListener("click",loadAll);$("addCustomerBtn").addEventListener("click",()=>openModal(customerForm()));document.querySelectorAll('#nav .nav-item').forEach(b=>b.addEventListener('click',()=>{currentView=b.dataset.view;render()}));
if(token){$("loginView").classList.add('hidden');$("appView").classList.remove('hidden');loadAll()} 

$("modalHost").addEventListener("click",e=>{if(e.target.matches("[data-close-modal]"))closeModal()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
